services:
  - type: web
    name: clinicai
    env: node
    buildCommand: npm install -g yarn@1.22.19 && yarn install --ignore-engines && yarn build
    startCommand: yarn start
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production

