services:
  - type: web
    name: clinicai
    env: node
    buildCommand: npm install --legacy-peer-deps --no-audit --no-fund && npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production

